import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/app/components/theme-provider";
import { ModeToggle } from "./components/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="flex justify-end md:justify-between items-center p-4 gap-4 h-12 border-b">
              <p className="bold text-xl hidden md:block">Baby Tracker</p>
              <div className="flex items-center gap-4">
                <Show when="signed-out">
                  <SignInButton>
                    <span className="cursor-pointer">Sign In</span>
                  </SignInButton>
                  <SignUpButton>
                    <span className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base  h-8 px-4 sm:px-5 cursor-pointer inline-flex items-center justify-center">
                      Sign Up
                    </span>
                  </SignUpButton>
                </Show>
                <Show when="signed-in">
                  <UserButton />
                </Show>
                <ModeToggle />
              </div>
            </header>
            {children}
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
